app: postgres

image:
  name: postgres
  tag: alpine

port:
  target: 5432
  node: 5432

pg:
  database: database
  host: localhost
  username: seshu
  password: "ENTER_PASSWORD_HERE" # TAKE CARE OF PASSWORD LEAKS!!
  data_dir: /mnt/c/Users/seshu/.postgres
  data_mount: /var/lib/postgresql/data
  timezone: Asia/Kolkata
