app: "prefect"
image: "prefect-image:latest"
server:
  port: 4200
  workpool: default-pool
postgres:
  configmap: "postgres-configmap"
  secret: "postgres-auth-secret"
  service: "postgres-service"
  image: "postgres:alpine"
insta_automate:
  src: "/mnt/d/Coding/GitHub/Insta-Automate"
  mnt: "/opt/prefect/Insta-Automate"
