app: prefect
image:
  name: prefecthq/prefect
  tag: 3.6.10-python3.14-kubernetes
port: 4200
pg:
  app: postgres
  image:
    name: postgres
    tag: alpine
workpool: default-pool
ia:
  project: https://github.com/SeshuTarapatla/Insta-Automate
  branch: prefect
  secret: insta-automate-secret
