apiVersion: v1
kind: Service
metadata:
  name: prefect-server
spec:
  type: LoadBalancer
  selector:
    app: prefect-server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}