apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-server
spec:
  selector:
    app: {{ .Values.app }}-server
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  type: LoadBalancer
