apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      volumes:
        - name: {{ .Values.app }}-data
          hostPath:
            path: {{ .Values.mount.host }}
            type: DirectoryOrCreate
      containers:
      - name: {{ .Values.app }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        env:
          - name: POSTGRES_DATABASE
            value: {{ .Values.db }}
        envFrom:
          - secretRef:
              name: {{ .Values.app }}-secret
        volumeMounts:
          - name: {{ .Values.app }}-data
            mountPath: {{ .Values.mount.target }}
        